#!/bin/bash

# FILEPATH: /home/s317703/assignment/tests/tests_order

# Declare an array to store the filenames
filenames=(
    "test1_first.S"
    "test1_second.S"
    "test1_third.S"
    "test1_fourth.S"
    "test1_fifth.S"
)

# Access the filenames in the array
mkdir ../.tmp
mv ../sbst/tests/test1.S ../.tmp/test1.S 
for filename in "${filenames[@]}"; do
   cp "$filename" ../sbst/tests/test1.S 
   cd ..
   mkdir reports
   make questa/lsim/gate-timing/shell
   wait
    ./run_fsim_campaign.sh 
    wait
    mv ./reports ./result/reports_${filename:0:-2}
   cd tests
done
mv ../.tmp/test1.S ../sbst/tests/test1.S 

